# Higher priority tasks have more control.
ROTATION = 1
FOOD = 1
INVENTORY_CHECKUP = 2
BUFFS = 3
MULE_POSITIONING = 3
INVENTORY_CLEANUP = 4
AP_DISTRIBUTION = 5

FAILSAFE = 29
ERROR_HANDLING = 30

ANTI_DETECTION = 90
KILL_SWITCH = 99
