from .test_bot import TestBot
from .ludi_freemarket_roaming import LudiFreeMarketRoaming
from .subway_magician_training import SubwayMagicianTraining
from .subway_magician_training_2 import SubwayMagicianTraining2
