from .ludi_free_market_template import LudiFreeMarketTemplateMinimap
from .kerning_line1_area1 import KerningLine1Area1Minimap
from .kerning_line1_area2 import KerningLine1Area2Minimap
from .mysterious_path3 import MysteriousPath3Minimap
from .path_of_time1 import PathOfTime1Minimap
